### ISSUE TITLE
Gradle - Failed to resolve dependancy

### ISSUE THREAD

**Issue by Ahmed-AlHahsimi-SEDRA** [Krobys/document-scanner-fast#1]
When adding this library into gradle, i get an error Failed to resolve dependency.
when I used AAR of the library it worked fine.

I haven't found much help online, but I assume this happens because of the difference in gradle version, I'm on 7.1.1 and this library is on 4.x.x

would you consider updating gradle and releasing a new version?

**Comment by Krobys** [comment]
Can you please provide more information about the error?  As for gradle, I'll look into it soon, thanks for the tip.

**Comment by Ahmed-AlHahsimi-SEDRA** [comment]
Hello,

sorry for the inconvenience, but i solved the issue:

It seems that in newer gradle versions there is a settings.gradle file as well as the build.gradle file

build.gradle looks like this and has `maven { url 'https://jitpack.io' }` as per the documentation of this SDK

```
buildscript {
    repositories {
        google()
        mavenCentral()
        maven { url 'https://jitpack.io' }
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:7.1.1'
        classpath 'org.jetbrains.kotlin:kotlin-gradle-plugin:1.6.10'

        def nav_version = "2.3.5"
        classpath "androidx.navigation:navigation-safe-args-gradle-plugin:$nav_version"

        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
    }

task clean(type: Delete) {
    delete rootProject.buildDir
}
```

but this change needs to be also reflected in settings.gradle file like so

```
dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        google()
        mavenCentral()
        maven { url 'https://jitpack.io' }
    }
}
rootProject.name = "My Project Name"
include ':app'
include ':MyCustomLib'
```
