### ISSUE TITLE
LiveDetection doesn't work

### ISSUE THREAD

**Issue by swiech-applover** [Krobys/document-scanner-fast#2]
Hi,

Thank you for nice library.

I've got problems with liveDetection. It doesn't work. I cannot see the rectangle and also autoCapture is not working. Any suggestions?

Best regards

**Comment by Krobys** [comment]
Hey, I'm surprised it doesn't work for you.  This library has been modified and improved by me, not created from scratch, try using the original one and tell me if it works for you.

Original - https://github.com/zynkware/Document-Scanning-Android-SDK

**Comment by swiech-applover** [comment]
Thank you for response. I've tested it on another phone and seems it works so maybe it's problem with previous device. You can close the issue. Thank you
